# Single - for unified NIC for WAN/LAN
public_ip: "100.100.100.162"  # WAN Address

interfaces:
  # WAN/LAN interface - handles inbound/outbound packets from clients
  - interface: "ens5"
    internal:
      subnet: "100.100.100.0"      # Internal network subnet
      mask: "255.255.255.0"
